version: "2"
services:
  client:
    image: th0rn0/smirkyisms-client:latest
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      API_ADDR: https://api.smirkyisms.com
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_AUDIENCE: api.smirkyisms.com
    labels:
      traefik.http.routers.client-http.entrypoints: web
      traefik.enable: 'true'
      traefik.http.services.client.loadbalancer.server.port: '80'
      traefik.http.routers.client-https.rule: Host(`smirkyisms.com`, `www.smirkyisms.com`)
      traefik.http.routers.client-https.entrypoints: websecure
      traefik.http.routers.client-https.tls.certresolver: le
      traefik.http.routers.client-http.rule: Host(`smirkyisms.com`, `www.smirkyisms.com`)
      traefik.http.routers.client-http.middlewares: redirect-https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: https
      traefik.http.routers.client-https.tls: 'true'
    networks:
      - external
  api:
    image: th0rn0/smirkyisms-api:latest
    restart: unless-stopped
    environment:
      MONGO_DB_HOST: mongodb
      MONGO_DB_PORT: 27017
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      UPLOAD_DIR: /mnt/smirkyisms/uploads/images
    labels:
      traefik.http.routers.api-http.entrypoints: web
      traefik.enable: 'true'
      traefik.http.services.api.loadbalancer.server.port: '1337'
      traefik.http.routers.api-https.rule: Host(`api.smirkyisms.com`)
      traefik.http.routers.api-https.entrypoints: websecure
      traefik.http.routers.api-https.tls.certresolver: le
      traefik.http.routers.api-http.rule: Host(`api.smirkyisms.com`)
      traefik.http.routers.api-http.middlewares: redirect-https
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: https
      traefik.http.routers.api-https.tls: 'true'
    networks:
      - external
      - smirkyisms-internal
  bot:
    image: th0rn0/smirkyisms-bot:latest
    restart: unless-stopped
    environment:
      API_ADDR: http://api:1337
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_BOT_USER_ID: ${AUTH0_BOT_USER_ID}
    networks:
      - smirkyisms-internal
  mongodb:
    image: webhippie/mongodb:latest
    restart: unless-stopped
    volumes:
      - smirkyisms-mongodb:/data/db
    networks:
      - smirkyisms-internal
networks:
  external:
    external:
      name: external
  smirkyisms-internal:
volumes:
  smirkyisms-mongodb:
